version: '3.3'

services:
  srv:
    build: ./server
    restart: always
    environment:
      QWE: "rty123"
    ports:
      - "8888:80"
    networks:
      - infrastructure
    volumes:
      - ../app:/srv

networks:
  infrastructure:
