version: '3.3'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  srv:
    build: ./server
    restart: always
    hostname: srv
    environment:
      QWE: "rty123"
    ports:
      - "8888:80"
    volumes:
      - ../input:/mnt/input
#    command: /bin/bash -c "/usr/bin/python3 /srv/fcdc.py"
